spring:
  application:
    name: demo-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    id: ${spring.application.name}:${random.value}
    #hostname: localhost